ModelBinding/Models/ErrorViewModel.cs
using System;

namespace ModelBinding.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ModelBinding/Models/Ogrenci.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ModelBinding.Models
{
    public class Ogrenci
    {
        public int OgrenciId { get; set; }
        public string OgrenciAd { get; set; }
        public string OgrenciSoyad { get; set; }
    }



    public class OgrenciContext : DbContext
    {
        public DbSet<Ogrenci> Ogrenci { get; set; }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Data Source=.;Initial Catalog=InternetProgramciligi;Integrated Security=true");
        }
    }
}

ModelBinding/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ModelBinding.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ModelBinding.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ModelBinding/Controllers/OgrenciController.cs
using Microsoft.AspNetCore.Mvc;
using ModelBinding.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ModelBinding.Controllers
{
    public class OgrenciController : Controller
    {
        OgrenciContext db = new OgrenciContext();
        public IActionResult Index()
        {
            var ogr = db.Ogrenci.ToList();
            return View(ogr);
        }
        public IActionResult OgrenciEkle()
        {

            return View();
        }

        [HttpPost]
        public IActionResult OgrenciEkle(Ogrenci ogr)
        {

                db.Ogrenci.Add(ogr);
                db.SaveChanges();
                return View(db.Ogrenci);
        }
    }
}

ModelBinding/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ModelBinding/Views/Ogrenci/Index.cshtml
@model IEnumerable<ModelBinding.Models.Ogrenci>

@{
    ViewData["Title"] = "OgrenciEkle";
}

<h1>OgrenciEkle</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OgrenciAd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OgrenciSoyad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OgrenciAd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OgrenciSoyad)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OgrenciId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.OgrenciId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.OgrenciId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ModelBinding/Views/Ogrenci/OgrenciEkle.cshtml
@model ModelBinding.Models.Ogrenci

@{
    ViewData["Title"] = "OgrenciOlustur";
}

<h1>OgrenciOlustur</h1>

<h4>Ogrenci</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="OgrenciEkle" asp-controller="Ogrenci" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="OgrenciAd" class="control-label"></label>
                <input asp-for="OgrenciAd" class="form-control" />
                <span asp-validation-for="OgrenciAd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OgrenciSoyad" class="control-label"></label>
                <input asp-for="OgrenciSoyad" class="form-control" />
                <span asp-validation-for="OgrenciSoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ModelBinding/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ModelBinding</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ModelBinding</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ModelBinding - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>